### ISSUE TITLE
im getting this issue trying to hook my auto gpt to coinbase

### ISSUE THREAD

**Issue by DirtyDan02** [isaiahbjork/Auto-GPT-Crypto-Plugin#11]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "D:\Auto-GPT\autogpt\main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Auto-GPT\autogpt\plugins.py", line 238, in scan_plugins
    loaded_plugins.append(a_module())
                          ^^^^^^^^^^
  File "D:\Auto-GPT\myenv\Lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class AutoGPTCryptoPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

**Comment by TheBigXion** [comment]
Having the same problem (Same message, everything), I think it's because the plugin is outdated. Tried to make it work with previous Auto-GPT versions, but they are too outdated to work with OpenAI apparently. Let me know if you find something that solves it

**Comment by DirtyDan02** [comment]
> Having the same problem (Same message, everything), I think it's because the plugin is outdated. Tried to make it work with previous Auto-GPT versions, but they are too outdated to work with OpenAI apparently. Let me know if you find something that solves it

I found a solution I will link everything I used to fix this in the morning

**Comment by TheBigXion** [comment]
Please do man... Im kinda desperate trying to make this work... Do you run it with or without docker?

**Comment by TheBigXion** [comment]
> > Having the same problem (Same message, everything), I think it's because the plugin is outdated. Tried to make it work with previous Auto-GPT versions, but they are too outdated to work with OpenAI apparently. Let me know if you find something that solves it
> 
> I found a solution I will link everything I used to fix this in the morning

Please do man... Im kinda desperate trying to make this work... Do you run it with or without docker?

**Comment by TheBigXion** [comment]
> > Having the same problem (Same message, everything), I think it's because the plugin is outdated. Tried to make it work with previous Auto-GPT versions, but they are too outdated to work with OpenAI apparently. Let me know if you find something that solves it
> 
> I found a solution I will link everything I used to fix this in the morning

Hey man, could you please share with me the solution that worked for you? Really need to get this to work
